use std::fmt::{Display, Formatter};
use strum_macros::EnumIter;

#[derive(EnumIter, Debug, Copy, Clone, Eq, PartialEq)]
pub(crate) enum Category {
    None,
    Amateur,
    Anal,
    AnimeGames,
    Asian,
    Bareback,
    Bdsm,
    Bears,
    Bisexual,
    Black,
    BooksMagazines,
    Chubbies,
    Clips,
    ComicYaoi,
    DaddiesSons,
    Dildos,
    FanSites,
    Fetish,
    Fisting,
    GreyOlder,
    GroupSex,
    Homemade,
    Hunks,
    Images,
    Interracial,
    Jocks,
    Latino,
    Mature,
    MediaPrograms,
    Member,
    MiddleEastern,
    Military,
    OralSex,
    Softcore,
    Solo,
    StraightOlder,
    StraightYounger,
    ThemedMovie,
    Trans,
    TvEpisodes,
    Twinks,
    Vintage,
    Voyeur,
    WrestlingAndSports,
    Youngblood
}

impl Display for Category {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            Category::None => write!(f, "Select Category"),
            Category::Amateur => write!(f, "Amateur"),
            Category::Anal => write!(f, "Anal"),
            Category::AnimeGames => write!(f, "Anime Games"),
            Category::Asian => write!(f, "Asian"),
            Category::Bareback => write!(f, "Bareback"),
            Category::Bdsm => write!(f, "BDSM"),
            Category::Bears => write!(f, "Bears"),
            Category::Bisexual => write!(f, "Bisexual"),
            Category::Black => write!(f, "Black"),
            Category::BooksMagazines => write!(f, "Books & Magazines"),
            Category::Chubbies => write!(f, "Chubbies"),
            Category::Clips => write!(f, "Clips"),
            Category::ComicYaoi => write!(f, "Comic & Yaoi"),
            Category::DaddiesSons => write!(f, "Daddies / Sons"),
            Category::Dildos => write!(f, "Dildos"),
            Category::FanSites => write!(f, "Fan Sites"),
            Category::Fetish => write!(f, "Fetish"),
            Category::Fisting => write!(f, "Fisting"),
            Category::GreyOlder => write!(f, "Grey / Older"),
            Category::GroupSex => write!(f, "Group-Sex"),
            Category::Homemade => write!(f, "Homemade"),
            Category::Hunks => write!(f, "Hunks"),
            Category::Images => write!(f, "Images"),
            Category::Interracial => write!(f, "Interracial"),
            Category::Jocks => write!(f, "Jocks"),
            Category::Latino => write!(f, "Latino"),
            Category::Mature => write!(f, "Mature"),
            Category::MediaPrograms => write!(f, "Media Programs"),
            Category::Member => write!(f, "Member"),
            Category::MiddleEastern => write!(f, "Middle Eastern"),
            Category::Military => write!(f, "Military"),
            Category::OralSex => write!(f, "Oral-Sex"),
            Category::Softcore => write!(f, "Softcore"),
            Category::Solo => write!(f, "Solo"),
            Category::StraightOlder => write!(f, "Straight older"),
            Category::StraightYounger => write!(f, "Straight younger"),
            Category::ThemedMovie => write!(f, "Themed Movie"),
            Category::Trans => write!(f, "Trans"),
            Category::TvEpisodes => write!(f, "TV / Episodes"),
            Category::Twinks => write!(f, "Twinks"),
            Category::Vintage => write!(f, "Vintage"),
            Category::Voyeur => write!(f, "Voyeur"),
            Category::WrestlingAndSports => write!(f, "Wrestling & Sports"),
            Category::Youngblood => write!(f, "Youngblood"),
        }
    }
}